cluster_context: apollo
k3s_version: v1.34.3+k3s3
extra_server_args: >-
  --node-ip={{ k3s_node_ip }}
  --advertise-address={{ k3s_node_ip }}
  --flannel-iface=enp7s0
  --tls-san={{ external_api_endpoint }}
  --tls-san={{ api_endpoint }}
extra_agent_args: >-
  --node-ip={{ k3s_node_ip }}
  --flannel-iface=enp7s0
