apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: pihole
type: Opaque
stringData:
    WEBPASSWORD: ENC[AES256_GCM,data:qlebidnU0KReI/D1BkSf6s+dvCvJjtqbaPLaLyNnS54=,iv:jFxnTquwmFfhTMxcRLE2WhfuZpEhQ21BbWVpN9mrPoM=,tag:wLBnrDGh2RMU48XOqwis7g==,type:str]
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeWJieGdiZGZVTG9vQ3JI
            cERTMHFWd2NDd3J2ZUcwekdQci9DUkp2ODEwCnNUQTNLZFdLK2E3cjB1NXpxM0NX
            eEdoSEd1OXpJNGx5NnlLWnpHbS9MUmsKLS0tIGw4WkxZTFZ4SW94R2NZcGJ2RFlZ
            dFltaEkrRFpsa3gwU1kydmFBZHQyY1kK5bifAStecAcMhu8VjD4NdI1mHRuaKk0U
            j9SgpD3/5XHSCeYr8NVMFtNxLM+arvSRCXElF+3v+q1SRbYshkeKmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T21:23:37Z"
    mac: ENC[AES256_GCM,data:GQ7m4jadPcjLNBUuAR18/3GGfco5OBSDuJYtlRqJXQ0yqrUaLsumGcFaGnJVP4stLKjZ3J14UwxZvjnxmG8kIh7tUcButVd1jAhWV7CqZhVIQKcI3PX5LbEjE6yRDBLBtcJbc4QXTRvQPrnqKf04qt1MsYjP+gbE4V3yWrugcBc=,iv:hG6rD8M+Ck2HACUV5kPZQi94M7X90afGDxsLaRFFcqk=,tag:iYOB0Pcdj7z4dFonsloOQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
