apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:aSuJ/oppdGtH9bubrYPcCes=,iv:hybOAEimagmMPxiUSX5WgYotp9XNp1+OWXeKGIfR4l4=,tag:jvQK9gDR+TqFF+rvnBOTVg==,type:str]
    client_secret: ENC[AES256_GCM,data:NNpXvRO1KEcFVTDqon0yXRmb6JoHm6/+nXToUYoG3OJ7d6btj6K5okkOf6E0/xHOeVvZJvxKyQkAf4O+Gnmz7g==,iv:3pivCxsm3CbvcMvUtyN2ouwEc6OhrKszxCdVpZ1b0Fk=,tag:soaTXI9FQ//RXeI/xLrNEA==,type:str]
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSHA3b05OS20xSkdybWds
            bVVpZUFXTEpHcGhGMlkvcVNWbEYzS2x2UUFJCjhFZXl2Z1Y1MVN4Q3lyYlJEMzVN
            UWNPemFPS2dVRjJZWjA1RnEyeWdXcU0KLS0tIGtIa0Jsblk5T0p6SmxhMjhvZkVr
            cXhhWWRqcG5zWGhRbC93U0NnczNUK2cKQjJLS0/M8fdeeXiTU+Od3AQjbuKkNfDX
            +KnMyhPVRI3sM1VkSnQkqSYDMdnd6EVZCZPrUDc4neXT1UiypQhh6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T21:06:13Z"
    mac: ENC[AES256_GCM,data:k6xehocSeR96r5ys/AaA5IPxdUnZIoxxSpl9PfK510R4O71H0g3nW/Vl5nGWj4ZHT03DeJQVhyatr6pQoMOYH4wp5fNRtbxvOCrxp4RuVINH2yaQZQ2Iim6hJdBJ7aqd2Nb6aCWW0XYQvMELgbd12hu7hvRXWR2xWPTPt7ypjj0=,iv:GOX45sOgeYug6qKemeGLQthzKQfRiYn0Olb9R/WdugE=,tag:CQ3RDiuyiMH2hmcqz3LwBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
