apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:ZkEndhNUSI8fqw1eDiNX9x8=,iv:gMCI2u5ZS6vMXWzCrgnlKLZUt9YMvyLxWE7smFbbcTk=,tag:5DnvwKvACjbrF/+aL/6Big==,type:str]
    client-secret: ENC[AES256_GCM,data:M1F88VKqBdv3WjtOxR6Vgwd/mX6VdVWInfNFsWzdmmZFgFB9VbWvUD/1CgIqSpB4tbQ49AhCnMJ8W14acGi3Eg==,iv:u2pJf4rw9Mv86SF4gKCY50b0GAUxunXahF9BqhY7Fbc=,tag:JG8vpRRktuLjJllLzqcNqw==,type:str]
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTzJydlRkRHMwL3RzbytN
            ZUNVWkJLSzVSbFdjRjdjNVJnb2N1WnErczJBClBMdHR4SVgyNGg4TVVjL1RVcENN
            Sm1uSHk2ZTBYN0lwUExVMG5lQUF5UFEKLS0tIEQ2MzJoYlB5cThsalY5WEtnd0Zy
            aWJrQ0pya05TbHZ1R2F2bmZFeVJOa1kKIz5LC0hRE4mmf78U4fCkDbRz3BfhPKRu
            pKst4dP1XuKo6f/6Q0tgPzcEl4rrXYytVoFrxdJZE1ZztG/a+ZrDlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T19:47:45Z"
    mac: ENC[AES256_GCM,data:9GZ2YAbryWgilV31gFKYgIIzLp0Or0sBReDh94Zc90lcC3a1cYnJmE8wE5cktcz6oBoz9/TcX9fbIzCiYq2dJ1aenZFOLXvfkqv3hJBNttqCkxViJPlnMJmp/hJ8YnlbLZp5d0Co5Hou/dK1hufXmbWy4bVrzh+LXi8Jh8/BYBQ=,iv:G93bmZu7lA/wn8pwuYaQRZvkRhMwbv61b6oS9Kc/45k=,tag:l/9WqX00Gh6aIrXpGNAfqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
