apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:v2E1YGWihN5HWUOfrKcElmPXqQv/0DgX4tjuvHHM074eLsS/3PgRcg==,iv:zWjwKkZ/EvAoDDZa5RAr9PTCBvIEd9jIfRkGThfwPqs=,tag:pj6QDn1DQ9ZlrwCHWSqqIQ==,type:str]
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTjljenQ5OG40WGh2K2Fz
            cWpoOVNOZWJZSUJicG1xRjVvZlhmZVVHNmxzCkhiZjZScVJMS3cvT3dqYWxIUDNV
            N1N3QkxMOVZZaTNiS0U4MVBvN3FmNncKLS0tIHlwSS9zdmU2bEVrTHRQRmYrYmNX
            YmJick9obG4zUXlvb1RUNHJXcE5oZzAKdYnVXBMvp0QFVwZxi6RZ0gSxzv3nr38Y
            TZvn8eeNaEiRshiSJV1jKJga/S8dY2WO65lROmiYBDdPALLuQZCpBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T12:41:28Z"
    mac: ENC[AES256_GCM,data:pzbwydwVoMHzoSqWvPDDVnvX/sDJJjTn8hry2ENg5p6dlMef73ClwPKKlVB4INNx9nb6NmoAAMQ+zOmh8+2WT/C/2iKremRtJIX8UXYG9rTm33D038/yOB0U141MSKA4HBDPd7fnmdqYCqGmRex+cJsi1NjSBTPgDRV/FH007Fc=,iv:zSNomHwKEYuxPvUgkaeuKWB24HskkcdCgaGyP7/H9Ac=,tag:PrsYQAFeWEJQXoPez1/bVA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
