apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  clientId: "359848657530454327"
  audience: "359848657530454327"
  authority: "https://auth.trai.ch"
  deviceAuthEndpoint: "https://auth.trai.ch/oauth/v2/device_authorization"
  tokenEndpoint: "https://auth.trai.ch/oauth/v2/token"
  oidcConfigEndpoint: "https://auth.trai.ch/.well-known/openid-configuration"
  managementApiEndpoint: "https://api.netbird.trai.ch"
  managementGrpcApiEndpoint: "https://grpc.api.netbird.trai.ch:443"
