apiVersion: v1
kind: Secret
metadata:
    name: netbird-secrets
    namespace: netbird
type: Opaque
stringData:
    IDP_CLIENT_ID: ENC[AES256_GCM,data:Xo4v9MZfR0SPAnjomWY0srf3,iv:bmrQe0kQnzOu3MpZWumOnsHASbB2DnVnArNLxk6e30A=,tag:mHI6WHcQegKeM6sSoZr7NA==,type:str]
    RELAY_PASSWORD: ENC[AES256_GCM,data:23gnddccMgWBjOfK8qiTAaTHQSl85RXxL42ic/apeXND0Rb1Flax9XyYTx8=,iv:qGfb2meXsGOAafxN47pXIwLrIjkMUje3dJaUXqaR7dc=,tag:Fo+upLYMv5/3xC0E/JyX/g==,type:str]
    DATASTORE_ENCRYPTION_KEY: ENC[AES256_GCM,data:x/IMDFeUa5FbOpgAH79hUykmzIymd8H8ijrxZ8r38NAJ4QeJy98qV7RbA9c=,iv:/xe2PouJiWte0Tx0xdhwEU9XW75CxO8fdsmblrqw8uQ=,tag:CCpor8H5JR8qhReZx6KpTQ==,type:str]
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOGk2dGUrOFRxY1dNYkNM
            M2pLVVVVMzF5cUc3WjkwRGxxVlVYeFJxZW1ZCm9UaXB6cHJtVG9kTlNFUUZZMVp0
            Q0lUbGUxSTRYMkl6cHZjb1p5TjVGSmcKLS0tIGxEY254YXB1ZGR4aGFkd0xJUGF5
            VnRmQWpERTM1OHJDUkNTZ01uV2hIdWcKvsJUX2GABLIQfstzi6pM3n1u58bDeaOt
            nA5tQWGKir4bDs9VW4r1r2NzU259kiO00ZcwJ/m2x2o7iVq5vqAE9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T00:49:48Z"
    mac: ENC[AES256_GCM,data:QK32pbRcplTd+HQfNFVMXgkjeKwzY61BNpD0sHRRpjw6SxqozqQrgnqdmX56tYkzvQ+AYRziLm24ZtBQvIApohuw0CBwDbXQafnixMnbS99XvYwcbOZQxh3aDuSCygTSIDsF+qct8nXb/lCcjdULbUy4XjlkAonLgntV/K29P1U=,iv:TAsdZqCFdTzrzEEFGJ8U3Ehd34gTNrTbKGpZYF02Opg=,tag:2t5tcOeVHXMCLVaiNxH0xw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
