apiVersion: v1
kind: Secret
metadata:
    name: netbird-relay-secret
    namespace: netbird
type: Opaque
stringData:
    netbird-relay-secret-key: ENC[AES256_GCM,data:6XV+LM+Q6eHvUhDnJ7LrCnTY6OkH0ch2iF0XZ7L07+6ecxstQuQzWsu0uLA=,iv:GNC///8GoMtT1GACfhrkZ5nBI2H7nNJTWwBl2sTiYxw=,tag:UNclq06Ic918jtiWtvkegQ==,type:str]
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUUswVHJ3VHBRd3NvUzZF
            eGNIQ0Z6cy9XT2M3MHZyU2k1cVRYd1ZPeVJ3CmpQcVdkOXdVTFAySVNBUVIwNUk2
            VzVDazBtRjNPSXZsZ1Z6WHhpRXgxUFEKLS0tICtwN21oRDdNT3RaNzJOeEhlRTBK
            UjJnbFhuTWNYNGJJU2ZVa2xqbmNvSzAKzj4nWcxckyGSDm+zm/CcDIFicVIbHrz4
            9sZXym5QRfOEB4A/xqJ9HJ+P/VO9DLhBRjcwC1VWec0NrMh+83wvKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T23:56:23Z"
    mac: ENC[AES256_GCM,data:oJ1MYgL1A07+fl0wFB/1k7pOs0Wqz4Kj2aFwBLEfe9/+M4K8ru8Qqgcxlxh/+6CiKsNdjj8I8knsxlFcRiIIuwMyMVLp/CSZKYJBH7E7z/lOJRjM1WNrzThLx8nunlLcMZBVyE6MvVZzcgGcLSLbg2NTok5M+K9HhDUuCgHXmZI=,iv:C2RvSD0bHqPzdXwbCylBy8FMdQoxBWKyKfImZvt18KM=,tag:5rmy1/mVL9pf3jB7oSQ2Kw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
