apiVersion: v1
kind: Secret
metadata:
    name: netbird-secrets
    namespace: netbird
type: Opaque
stringData:
    IDP_CLIENT_ID: ENC[AES256_GCM,data:o4MHbOZPAGWZGBqTIdPpnfxh,iv:aoh+AiR4csz9EXdkYoxt/mWLhZWcshWW7V26PfnNiUw=,tag:5CL1pQTLcKxZK9zTJcoQoQ==,type:str]
    RELAY_PASSWORD: ENC[AES256_GCM,data:UkpluUWaNEN8S58DQBvlIYbJbHfeyiW+2G/7KDwl900=,iv:X7aIRl9dqe8BrH0ydRhIQL/bi+pP8JEdoxgbDMTinwM=,tag:peRuDmxacFpLWRi2q/lnfA==,type:str]
    DATASTORE_ENCRYPTION_KEY: ENC[AES256_GCM,data:JXLP0eN+hMMYEwufFhPiPCK3fTH0N5aHGBEj2dKVrxE=,iv:vxiARFIzEbyCYIwJI3A2mo5wYU05qE4k/9o/+gvK8t4=,tag:PYHVbXsfeaOeQjyUk8ciVQ==,type:str]
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOEl1Tk1OOGdyNkJYSEtG
            SE1wOTVsZVM5SlhPd0ZTTWFUaU92c2lLTDJNCjRsTmxnQ0FreFFnMlBaelJlZm8z
            MjhDQUtuL2xSKy9ESGF3d0tQaGNhQzQKLS0tIHdwS0NhU3doODA2SjA1UHJIam93
            RWl3Q0thN0RkNlFBeEh6aE5kVVYxdFkKCZ8F6QHa6EdFSAxg0gRqUybR7ZTpg/AG
            fTelrkQpajHFvtcJ6a3qfJyf5HzW0U0ZoyK6g58n6QpvBVDalhKlKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T00:38:45Z"
    mac: ENC[AES256_GCM,data:lSVBNSHEkozDb/Yx4ptVYqxKhTY7WSLljzSHr9Hw/VCtZsAZQOqqC8EciaHFG+jeVH9OM1067EyJa7b4XCs5lYIRPSNPBfIi7nFOlUHmoNZmuzeg1c4N4gVXowIBCjHyvZgcS2Mnuvy/uOjLkBpMXvHJG4ji3wxsfZcNy+SSUoA=,iv:7gEQLTyh3GOMrrif9iGuSSBBqzUamd1xYxBvOOCKLAY=,tag:gUUwgkVzRrdrQC4tjOHMJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
