apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchenowl
  namespace: kitchenowl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchenowl
  template:
    metadata:
      labels:
        app: kitchenowl
    spec:
      containers:
        - name: kitchenowl
          image: tombursch/kitchenowl:latest
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET_KEY
              value: "ChangeMeToSomethingSecureLater" 
          volumeMounts:
            - mountPath: "/data"
              name: data-volume
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: kitchenowl-data
