apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kitchenowl
  namespace: kitchenowl
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  tls:
    - hosts:
        - kitchenowl.home
      secretName: kitchenowl-tls
  rules:
    - host: kitchenowl.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kitchenowl
                port:
                  number: 80
