apiVersion: v1
data:
    JWT_SECRET_KEY: ENC[AES256_GCM,data:fZdT64gIWMO8+YS5ZT2PCB6Mtp2HQCCV83OcbvjBOi2+YxeXPSg8lgwt+cBaRrpHDtC0NdVX8Oz/OHz5vREVAxz75ltSiSFbqFj14JLU4DKpcjxq8g294g==,iv:Va8uhxTQ7IlBnkXoZM0WC3tPJ+mNCgwGBfQGT/ODuVo=,tag:g+qq9ctcY4uo/jhTd0jlBA==,type:str]
kind: Secret
metadata:
    name: kitchenowl-secret
    namespace: kitchenowl
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT1dyVXEwNHg4bmpiQnJt
            cjRzTk84cm15cXo3YVBnN2Z2dExGcFR6bVY4CjBESEYzL0FpdXpMOFN5ZmpCa05u
            YmhQSDVHRmFNUlRXbUxJVGdENmNjN3MKLS0tIEhvZTZPTi9oQ2drSngwcy9hS2ZX
            dU5wQWdHaGV4K1BhK054aHJEQTVuZ1UKjRY7FIWU8Spa5rjHiqmv9BMZlFaPFml9
            IdaF8na2viVJInxyS8yJEAabShuSeuUw0wdHHKZWVVXvQa8CYgwZmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T18:47:05Z"
    mac: ENC[AES256_GCM,data:h3QBynL5TNcphttAMKhaGK7IkB8Rl3QYQ4T7rGTTWVku6syFk+NTYZCqDsw+TN/eBQ2AkldmoXGZx7YRgEZJ93YalKbFG2vb3mHp0R/FNArFdtNrewP1xgSyPEtBJ0a4aTGYDnNLR6IdokQNDgrUTg2DsLlolsM45bPwhopiSsI=,iv:eCCTkcNpq6rl0l/4lh08qPrs5z/rzvBUzchqNDELMV0=,tag:Iua8Vaz20XzdQxawwcyhvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
