apiVersion: twingate.com/v1beta
kind: TwingateConnector
metadata:
  name: connector-1
  namespace: twingate
spec:
  name: k3d-dev-connector-1
  
  imagePolicy:
    provider: "dockerhub"
    schedule: "0 2 * * *"
    version: "^1.0.0"
