apiVersion: twingate.com/v1beta
kind: TwingateConnector
metadata:
  name: connector-2
  namespace: twingate
spec:
  name: k3d-dev-connector-2
  
  imagePolicy:
    provider: "dockerhub"
    schedule: "0 3 * * *"
    version: "^1.0.0"
