apiVersion: v1
kind: Secret
metadata:
    name: twingate-secret
    namespace: twingate
stringData:
    TWINGATE_NETWORK: ENC[AES256_GCM,data:wNCjvA==,iv:u9JRP+6a+2Iv1uOA7Fc1PD/ZconO6A+/HSlS+JBnVe4=,tag:FRiYpzjuaYmGpmXz6+q7bg==,type:str]
    TWINGATE_API_KEY: ENC[AES256_GCM,data:YVMZNGYjVspzAPRlCT9t6ruO4QElUtPQZ63fSnH6kC+qeUEB5cls2CvBoTd40z0apALw6w1ZR8WGkQWS2uTGEvWfjFh+C4o1RAFfv53RLbVTXth0CXN7wrX1ccDjeBS7TViMv0GeEhOVOe2TVaW6x3vDV9i/7wxh8WtZTTPORg1TSMysASw=,iv:5tpbtqHVsq9utuTlLpU3EIjafDOgk/QJE6TRGPHcLfs=,tag:0qKaOEx6q2ZpkiEtrcDQfA==,type:str]
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Y3ZEekJIZFRmdWZsL1ZQ
            dlExTjJWcUs2WGhaWXB6aklUZlpISEdMQkVnCkh2Szh6bzQ0Y2ZkalVDd3lXWUZF
            emdFc3dBNjZXRkl5dXJzV0pBYlhyS2sKLS0tIHV2bm1jSElBRzdFV25RdTBocE1i
            ZzFUZVA1YjRtRjlLaFJ6NVVWdXk1a0kKLFpnE3ZtcfExJ+kYyp05dX6NhOcAJs2S
            nLxhKAP5G8plpBPIkpQG842rI6pBxvajPA1VROhwK+aY6soX9jB60g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T22:49:50Z"
    mac: ENC[AES256_GCM,data:h8dmK4e2MO9Bg52keZqVGZNU6WL+X600L91W2UDc3tnyXQIH9zhq9QFETDdfHoZIW0YjrqeRjr3BTwfanahE3gq9vPF+sB+DVQgeevNJPNveAAuT3yyTbc6n2b0622lam5CgqfK80XBdTh0yMOFsEo2169U4rVo197588dKa1Rw=,iv:bA5lZb/v6yWc44xK6COLDRVr3d+E+5NLWV+pDZ0vKYs=,tag:iMjGLuM3kZVOB2TVg6AUng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
