apiVersion: v1
kind: Secret
metadata:
    name: twingate-secret
    namespace: twingate
stringData:
    TWINGATE_API_KEY: ENC[AES256_GCM,data:iOP+j42dTq/Q0E7lSvfBzqqQw436f11G42Z+9CwqCSqa4mlapfU4CZAZ/oeAnGLeG/tUY2vNRhAGBOudrTbay/b9Oo6ypZtW+9+nSteQa9JoxaymvuW1LKsUsYCmTKjIXTHqoWET3gDgmWDJ+JRDtUEYQSm5rNPLBLocFsNb0ap8V0by5Xo=,iv:TzBIcuqu/FqMycWtAtMshgdNAN6gGD0Q3FLA3+/gLbU=,tag:Uf0RhvPmTNy/NHaPp9R1bg==,type:str]
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeWxmUWNFZE9DS2VtZ00v
            UVFzaENpcEZsVVVWd2RiSTB3RlFkZmtLeHdNCjVwcXZ1NDgwN21sZmtSRXNpUXZD
            M3k2SFpuM2txTzZrcXcwVXJuK2FJaFkKLS0tIDQwRDJuQVl0dDk4NzdFbnZTbzd2
            UURWbHRRWkxsSm8yT0hXTy9hY2sxakEKAnnUmUUn/bvwZiGrSv9G8i9y//jjFX5U
            O/Nupmj8RRCEt2pfM7lthquT0TxJGrS7yDdc7ax3BW7ivMmQg8MAYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T23:35:21Z"
    mac: ENC[AES256_GCM,data:qISUC5fLtOGdhce7WMic99S4AkApWXHkDwcPGaX5BongANRIAskaXqrGfAm4OKrKkukYHMxrhi8E+rrQ32CVvSdLGXSfzykHRpc0772LRy0hAYnLuCO+JwJO07dnqmFWlNKPdS8M+xMr1hnpPZBDPqelogK94+GpaxwZo1CiYVw=,iv:CJJy7zmku2ZLIl3iKl5a7CnI1+Qxz3TmwFgLZfr9PgM=,tag:N0hMx+3x/84Ci3+1FLDUYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
