apiVersion: v1
kind: Secret
metadata:
    name: zitadel-backup-credentials
    namespace: zitadel
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:1Xkg4nhAXwpVv66UughzRZIeAqA=,iv:JX5boJRjeiDp3T+svglT3qnCsjo9oiQY9/x9lMIqdeI=,tag:TR8wjvyCLNenRQ52HDwhOA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:rtmN3BzXp7cIVnvVtXlDqWxT+EI=,iv:YTVEHhHr39hAk5DR3e/XWT+O2sOroj29Q6a2fVHusWI=,tag:xgMCPuQzInvY3SwIuXML0Q==,type:str]
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcWtGUG1zaHpGWVoxTjg5
            MGhoNFNVeTNQSjQ0L2tkRE4xa1JpTjFoZWp3CmsxTjVPQU1SbCtLV0xRYStrMUoz
            TUNwYnpoOExPN0FGL1FwQUlPaFBGNU0KLS0tIE4yZmp3d3d5cklLR21obUxGUHVT
            My9tUXNHUUZodVZmOFZ5YjduK21ZMEkKmkqhH3UPMu4rNigvXpdXRVm4MaKs9pyX
            hH69roFx/G/rVTrlhgJRo3Ucb/9k/8Ma2IOWX9aGb1KcxBoP66FY5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T09:03:30Z"
    mac: ENC[AES256_GCM,data:18tQYoJf/nwO1iR2N+Q6u5XD5qlFyr6MtT8YTf8QbYx3RkGIbRhIy66v/t3+rUks5Jyu68RPRGn8zgfEfxH2gr0tzk4iJR6mgPb5UVFzr/vXSdKNrx4QsIMT5QoKXw3Zhr9nahCC99bCdauJ4rpK1MfrTLbSZPEPQ5YyisgKCd0=,iv:THFnp2LLRKsCAtDtPZJp2MBGHUZxuYR5ywN1eBvVPJ4=,tag:5mLoHiKWNPPDnIbKhNo+Sg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
