k3s_token: ENC[AES256_GCM,data:wOgZBSrYhWOX2QXrHosCWf9tQMoiVUDJiDBS8h+8fm8fE3Zi2ZgWTMoeQwI=,iv:ZQFGlPMvOX4F1xYnIn0o8OrWm8bfQ1ctlQIpqYaKkwI=,tag:3pk7+S6LgFqVoE/jJXAJyQ==,type:str]
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bUZrQU5WSWtPeWVNdmxY
            R0p3bkM2cmtPUnVZZFJvdjhZYzBDRS9UVDFvClJndmlEL1kxTTZkMjdwWkswRmxk
            Vko0dC9YM1VCWkZpWE40NmxneFhvT0UKLS0tIFUzWXROd3hmbGtxMlRTN0IyMURD
            N3E3VS9pWE05dkNlOHowZFJiOEhpQW8KFQloKxS/n2hXBv/NwobrwJ3opG0frG6f
            7BuTyb/dbGOGm/Hpen5u9WvHGs9VXsrJJ/9ZYdU3Z70trsmlymdXmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T11:39:29Z"
    mac: ENC[AES256_GCM,data:U4udJjtle0Vwt+jzYIZb00Bvkjf0cmnokOOE6nQr5W/Vp8zL1Hz0wURaDLQx8KOp1d+YaPm9FlcIk5OcWy+QzcsiioDXCJl7Vh9lAlhnetlktqRo0kqV/qpy0bStBq7Mmfl2NpVLJsDq8/dcCq0xAJWbyMRkYp1K4+JaPUY+bfY=,iv:W6TY4U/ePpUNSl/m+BG3OrIOCHzKXo60jJSXivG6DhI=,tag:Mxgnyw7acuDBtzqSp7WjsQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
