k3s_token: ENC[AES256_GCM,data:D/9XliqBZXf5CtUbyTeyFIgojLym19rs7L4ObtG/ix2kKHTl6REg6I3gVcE=,iv:/Kk8CSRDKC2CpHG7Jngjcymhn93rnnlTipjHXoh1pN8=,tag:T9eB0idoTik5JyOh4d/uzw==,type:str]
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVmNjd2tYTFgyaTJYbCs4
            cEpHM043U0hEVGJEajVZdExxQWdHa3AwZXdnCkF1OWVLR05ONzFsKzZvYWVrRUw4
            TUdhS0NlNUFBcGoyUmxRQy9tNUVwMzgKLS0tIHBvTmh6YWIwY2N3ZjBVQkVxczIv
            MVVjU3ZMK2RrejQxcjkydnFoSXIyNTAK/pJoo4XGA7bVz6Ue1nlcJ9i/p7kq8kTn
            FPYE5tvC7c5rumkstoVwdwzO+kuI9B7HOwzr4Y/PIValUuH0rKP/hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T10:13:06Z"
    mac: ENC[AES256_GCM,data:NcupzsnISHfh3Q/oqyReDOgLAY7OUqlokqoOqXUayCmoA8lENpBSFPIWfByLVY8YZAvxn2nTrgjlAKYIMAW79NLXdUFPlilsUrxyNtmNZFxaoKV5kK6Eg4uUO9yrmhK+IjvzlytOx6WSCGh6t/sjZ24wYPxXLM7lY3PHaYbwWvs=,iv:G3nDJ6HBnn6Rjn5sjmHtrb9Vqa79ybDn+w8kzQg9IWY=,tag:5vvWhN1/BdWC8dT/CLwQHw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
