apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: zitadel-db-backup
  namespace: zitadel
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: zitadel-db
