apiVersion: v1
kind: Secret
metadata:
    name: zitadel-masterkey
    namespace: zitadel
type: Opaque
stringData:
    masterkey: ENC[AES256_GCM,data:hZXSauZcU/oMb/+vErFzWoj9iW62G8sxxEbJjMXi+0MBaPs=,iv:2/vewf9DUw9mzlY0PCwQpxAQ7s5MOhORXKQuLKFCjUI=,tag:Y30VckzRzq8zQBeENn+GBw==,type:str]
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTjZEVzlKRVZQaUpjeDVI
            bFhISDQ1RFY1OVpsNjl4azRGSENlRjhpNTFBCjRMVlpWYTUwS295amw5QjdaeEU2
            QVdGWTFkaVhBLy9LTmdtN0JVVTJzVEEKLS0tIDJlTGZ0VGRuR2tzT3pseWlGTmt0
            VDgxd0xGYkk5dnIxaHQzUHJTd1ZvdlEKEvOmQQ9NFouKVjE7SncVMILXnEXj1yMW
            2XNPtsxTjT3PN/5RpG/iLdNr8ITfUzuhQALcWWw1eQp8xCMVknW6Qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T00:28:46Z"
    mac: ENC[AES256_GCM,data:ym0YZO5550m3GehaO+2Y3la9UY85l5BJcYsm0YS2seihN+/WOaAzYFqcKvE/9wRIbfvL6Ks41KjFE1kN29mBEsa4+dP/1SzCPicLV3E5yAM3j7jJ1aQyqTGKHlSsIRvwT3nrfZg+IPM0ZzodoVPGIzg0uCrCmFqJ2JjT+cjjM4g=,iv:A1nRBaC7M6adzLD03vM49NDubjjQr2HCAkqFpVTQke4=,tag:TjRw9qo9wzc06ZIZCakjcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
