apiVersion: v1
kind: Secret
metadata:
    name: zitadel-masterkey
    namespace: zitadel
type: Opaque
stringData:
    masterkey: ENC[AES256_GCM,data:7/Pbt3HovHRb10ElEJlzvQALYlUIGtM4na3YlkNaTDo=,iv:/JZcj05cL2WmTTH7s8TISikZPEz8uMT+6kwZ/4Xlgyg=,tag:Efoi6W1vGizKWN9Xp54GJQ==,type:str]
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINFdjcjFSSFhsVXlCMXBy
            eUMwVVljWjlPazFyQTYvUmEzUlBkVkUxaURnCnRuMWh3S0FxN2Q3OUlLQ2dKYUJq
            T29aQmdCSmZkWkJCdVhVZmtzUVVTMzgKLS0tIHUzMmsvVzh2WkZKcU9ZYzg0ZnBZ
            R015cERlUWhrYjJxYkZDTVhqUG9rdWsKzwTAEwNMw382uf9+oA52Hr8+5wzatoIq
            b+v0eI+evjZTlq7v98gQ7Drhr4fxxaFC1szfLcVduQ8EXu9sx19CDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T01:00:23Z"
    mac: ENC[AES256_GCM,data:eMsP3UoEMPEpbxS7aoWScR24ZWVge2llKTUot+OF+EvL5eG5XWyvilO11VNXHDeAu1M6HpMQonfL6QkDvgydahaIAkDO3VgTvqbGCKji9SpH8dx53mkrr3DPfvK0uGhYh4CZPJvC649i8h/YEmCePxVoKDTiSyW7HpqFKB19oaU=,iv:2wwL0L1LuB3/7ycHueEiR13En7SMurbKGpwvQ+9Tdps=,tag:T5fKHI4CJvCmbB8sN3TgTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
