apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-admin
  namespace: pihole
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: pihole-redirect-to-admin@kubernetescrd
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  tls:
    - hosts:
        - pihole.home
      secretName: pihole-tls
  rules:
    - host: pihole.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pihole-dns
                port:
                  number: 80
