apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: pihole
type: Opaque
stringData:
    FTLCONF_webserver_api_password: ENC[AES256_GCM,data:5ni7LVezwjcmp6vpnSOBnGu7WBfetVISNpVxh17ldIE=,iv:+mDi8/qemEu1Ckgg8VTYyaLj0rOX2kLd85e7TOSAF9g=,tag:MHOPYig1Te4OfI6JZulqjw==,type:str]
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTnk4aDh6N0dBeFJtNjFW
            Z09PYkgvdmlkWFRDNGdlZXlTa25xZU03WUVrCjVPY1BDaTB4bWdZYWxFNzNkT2Jm
            bWhZL1dsMWxOazJZQ0dSWjgvSzV1OE0KLS0tIE5mL21NRnBUREdRanVReHJ4eDVz
            N1FEMTAyYUY1Z1VTa2xqenFHVEZyMXMKFJk0RCaoekaIRMU/jm09AgDtcH77mI0d
            oIxgdhEL3GT9r87ZlnGvfiIx08gZaC7YCAWNIlq6IvMPxktGQOk7lA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T22:08:23Z"
    mac: ENC[AES256_GCM,data:SukSv3a9bMJHR9W4MJ5lazpMnXGIlzD0rn8+oLWffuCu7TJRGdolAHun3LXqoDaeyeHddIAcdSKO5fsnRz+Tr28cOFCS4deJf5VfBKkCWrUg3oG8WBZBL7TTOpEZh6YTDMPWJNNXtjbSj6rJJxO9RZ32qZrCM8RF+A+dMmAUfzQ=,iv:tIxwvzsDnfiHphu+n93qIUF/J6a3kdeeUXEllYbVBqM=,tag:koSLcqucoiTTiX15Z/aTkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
