apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: luca-fondo-cluster-admin
subjects:
  - kind: User
    name: luca.fondo@trai.ch # This must match the user in your error logs exactly
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
